export enum Style {
    Primary = 'primary',
    PrimaryOutline = 'primary_outline',
    Secondary = 'secondary',
    SecondaryOutline = 'secondary_outline',
    Success = 'success',
    SuccessOutline = 'success_outline',
    Danger = 'danger',
    DangerOutline = 'danger_outline',
    Warning = 'warning',
    WarningOutline = 'warning_outline',
    Info = 'info',
    InfoOutline = 'info_outline',
    Light = 'light',
    LightOutline = 'light_outline',
    Dark = 'dark',
    DarkOutline = 'dark_outline',
    Link = 'link',
    LinkOutline = 'link_outline',
}
